import { Vehicle } from "./types"

export const fakeDb: Vehicle[] = [
  {
    identifier: "a-20g",
    country: "usa",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 2.7,
    realistic_br: 2.7,
    simulator_br: 3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 16000,
    req_exp: 9200,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a-20g.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a-20g.png",
    },
  },
  {
    identifier: "a-26b",
    country: "usa",
    vehicle_type: "stormovik",
    era: 4,
    arcade_br: 5.3,
    realistic_br: 5.3,
    simulator_br: 5.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 185000,
    req_exp: 27000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a-26b.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a-26b.png",
    },
  },
  {
    identifier: "a-26b_10",
    country: "usa",
    vehicle_type: "stormovik",
    era: 4,
    arcade_br: 5,
    realistic_br: 5,
    simulator_br: 5,
    event: null,
    release_date: "2017-09-14 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 155000,
    req_exp: 46000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a-26b_10.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a-26b_10.png",
    },
  },
  {
    identifier: "a-26c",
    country: "usa",
    vehicle_type: "stormovik",
    era: 4,
    arcade_br: 5.3,
    realistic_br: 5.3,
    simulator_br: 5.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: true,
    value: 185000,
    req_exp: 54000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a-26c.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a-26c.png",
    },
  },
  {
    identifier: "a-26c-45-dt",
    country: "usa",
    vehicle_type: "stormovik",
    era: 4,
    arcade_br: 5.3,
    realistic_br: 5.3,
    simulator_br: 5.7,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 54000,
    ge_cost: 3850,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a-26c-45-dt.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a-26c-45-dt.png",
    },
  },
  {
    identifier: "a-35b",
    country: "france",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 2.7,
    simulator_br: 3.3,
    event: null,
    release_date: "2017-10-27 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 22000,
    req_exp: 11000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a-35b.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a-35b.png",
    },
  },
  {
    identifier: "a2d",
    country: "usa",
    vehicle_type: "fighter",
    era: 5,
    arcade_br: 9,
    realistic_br: 7,
    simulator_br: 7,
    event: null,
    release_date: "2019-05-28 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 95000,
    ge_cost: 6900,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a2d.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a2d.png",
    },
  },
  {
    identifier: "a5m4",
    country: "japan",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.3,
    simulator_br: 1.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 2100,
    req_exp: 4000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a5m4.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a5m4.png",
    },
  },
  {
    identifier: "a5m4_hagiri",
    country: "japan",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.3,
    simulator_br: 1.3,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 2900,
    ge_cost: 250,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a5m4_hagiri.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a5m4_hagiri.png",
    },
  },
  {
    identifier: "a6m2_mod11",
    country: "japan",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3.3,
    realistic_br: 3.7,
    simulator_br: 3.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 16000,
    req_exp: 9200,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m2_mod11.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m2_mod11.png",
    },
  },
  {
    identifier: "a6m2_n_zero",
    country: "japan",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 2.7,
    realistic_br: 2.3,
    simulator_br: 2,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 10000,
    req_exp: 7900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m2_n_zero.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m2_n_zero.png",
    },
  },
  {
    identifier: "a6m2_zero",
    country: "japan",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 3.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 22000,
    req_exp: 5600,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m2_zero.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m2_zero.png",
    },
  },
  {
    identifier: "a6m2_zero_china",
    country: "china",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 3.3,
    event: null,
    release_date: "2019-10-29 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 18000,
    ge_cost: 1300,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m2_zero_china.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m2_zero_china.png",
    },
  },
  {
    identifier: "a6m2_zero_usa",
    country: "usa",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 3.3,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 18000,
    ge_cost: 1300,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m2_zero_usa.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m2_zero_usa.png",
    },
  },
  {
    identifier: "a6m3_mod22_zero",
    country: "japan",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4.3,
    realistic_br: 4.3,
    simulator_br: 4,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 76000,
    req_exp: 13000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m3_mod22_zero.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m3_mod22_zero.png",
    },
  },
  {
    identifier: "a6m3_mod22ko_zero",
    country: "japan",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4.7,
    realistic_br: 5,
    simulator_br: 4.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 105000,
    req_exp: 17000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m3_mod22ko_zero.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m3_mod22ko_zero.png",
    },
  },
  {
    identifier: "a6m3_zero",
    country: "japan",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4.3,
    realistic_br: 4,
    simulator_br: 3.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 47000,
    req_exp: 18000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m3_zero.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m3_zero.png",
    },
  },
  {
    identifier: "a6m5_zero",
    country: "japan",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4.7,
    realistic_br: 5,
    simulator_br: 4.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 76000,
    req_exp: 26000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m5_zero.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m5_zero.png",
    },
  },
  {
    identifier: "a6m5_zero_china",
    country: "china",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4.7,
    realistic_br: 5,
    simulator_br: 4.7,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 40000,
    ge_cost: 1750,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m5_zero_china.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m5_zero_china.png",
    },
  },
  {
    identifier: "a6m5hei",
    country: "japan",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5,
    realistic_br: 5,
    simulator_br: 4.7,
    event: null,
    release_date: "2021-03-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 185000,
    req_exp: 27000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m5hei.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m5hei.png",
    },
  },
  {
    identifier: "a6m5ko",
    country: "japan",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5,
    realistic_br: 5.3,
    simulator_br: 4.7,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 54000,
    ge_cost: 3850,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m5ko.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m5ko.png",
    },
  },
  {
    identifier: "a6m5otsu",
    country: "japan",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5,
    realistic_br: 5.3,
    simulator_br: 5,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 155000,
    req_exp: 46000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m5otsu.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m5otsu.png",
    },
  },
  {
    identifier: "a6m6c",
    country: "japan",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5,
    realistic_br: 5,
    simulator_br: 4.7,
    event: "battlepass_season4",
    release_date: "2021-07-28 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 46000,
    ge_cost: 2980,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a6m6c.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a6m6c.png",
    },
  },
  {
    identifier: "a7he1",
    country: "japan",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 2.3,
    realistic_br: 2,
    simulator_br: 2.3,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 7900,
    ge_cost: 700,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a7he1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a7he1.png",
    },
  },
  {
    identifier: "a7m1",
    country: "japan",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5,
    realistic_br: 5,
    simulator_br: 4.7,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 46000,
    ge_cost: 4080,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a7m1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a7m1.png",
    },
  },
  {
    identifier: "a7m2",
    country: "japan",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5,
    realistic_br: 5.3,
    simulator_br: 4.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 185000,
    req_exp: 54000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a7m2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a7m2.png",
    },
  },
  {
    identifier: "a_109_eoa2",
    country: "italy",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 8.7,
    realistic_br: 8.7,
    simulator_br: 9.3,
    event: null,
    release_date: "2020-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1000000,
    req_exp: 380000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_109_eoa2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_109_eoa2.png",
    },
  },
  {
    identifier: "a_10a_early",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 10,
    simulator_br: 10.3,
    event: null,
    release_date: "2022-03-22 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 220000,
    ge_cost: 9090,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_10a_early.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_10a_early.png",
    },
  },
  {
    identifier: "a_10a_late",
    country: "usa",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10,
    realistic_br: 10.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2022-03-22 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 710000,
    req_exp: 260000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_10a_late.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_10a_late.png",
    },
  },
  {
    identifier: "a_129_a",
    country: "italy",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 10.3,
    simulator_br: 9.7,
    event: null,
    release_date: "2019-10-29 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 390000,
    ge_cost: 9090,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_129_a.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_129_a.png",
    },
  },
  {
    identifier: "a_129_cbt",
    country: "italy",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 9.7,
    realistic_br: 10.3,
    simulator_br: 9.7,
    event: null,
    release_date: "2020-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1020000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_129_cbt.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_129_cbt.png",
    },
  },
  {
    identifier: "a_129_d",
    country: "italy",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 11,
    realistic_br: 11.7,
    simulator_br: 11.7,
    event: null,
    release_date: "2023-10-31 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1030000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_129_d.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_129_d.png",
    },
  },
  {
    identifier: "a_20g_30_ussr",
    country: "ussr",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 3.7,
    event: null,
    release_date: "2022-10-26 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 26000,
    ge_cost: 1450,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_20g_30_ussr.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_20g_30_ussr.png",
    },
  },
  {
    identifier: "a_29_hudson",
    country: "china",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 2.3,
    realistic_br: 2,
    simulator_br: 2,
    event: null,
    release_date: "2019-09-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 10000,
    req_exp: 7900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_29_hudson.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_29_hudson.png",
    },
  },
  {
    identifier: "a_4b",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9,
    realistic_br: 8.7,
    simulator_br: 9,
    event: null,
    release_date: "2020-03-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 380000,
    req_exp: 135000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_4b.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_4b.png",
    },
  },
  {
    identifier: "a_4e_early",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9,
    realistic_br: 8.7,
    simulator_br: 9.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 450000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_4e_early.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_4e_early.png",
    },
  },
  {
    identifier: "a_4e_early_iaf",
    country: "israel",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9,
    realistic_br: 8.7,
    simulator_br: 9.3,
    event: null,
    release_date: "2021-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 520000,
    req_exp: 94000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_4e_early_iaf.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_4e_early_iaf.png",
    },
  },
  {
    identifier: "a_4e_late_iaf",
    country: "israel",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9,
    realistic_br: 8.7,
    simulator_br: 9.3,
    event: null,
    release_date: "2021-10-26 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 190000,
    ge_cost: 8910,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_4e_late_iaf.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_4e_late_iaf.png",
    },
  },
  {
    identifier: "a_4h",
    country: "israel",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 8.7,
    realistic_br: 8.3,
    simulator_br: 8.3,
    event: null,
    release_date: "2021-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 380000,
    req_exp: 135000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_4h.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_4h.png",
    },
  },
  {
    identifier: "a_4n",
    country: "israel",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.3,
    realistic_br: 9.3,
    simulator_br: 9.7,
    event: null,
    release_date: "2021-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 620000,
    req_exp: 220000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_4n.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_4n.png",
    },
  },
  {
    identifier: "a_5c",
    country: "china",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10,
    realistic_br: 10,
    simulator_br: 10,
    event: null,
    release_date: "2021-09-07 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 260000,
    ge_cost: 9270,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_5c.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_5c.png",
    },
  },
  {
    identifier: "a_6e_tram",
    country: "usa",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10,
    realistic_br: 10.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2022-12-20 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 260000,
    ge_cost: 9270,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_6e_tram.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_6e_tram.png",
    },
  },
  {
    identifier: "a_7d",
    country: "usa",
    vehicle_type: "bomber",
    era: 7,
    arcade_br: 10.7,
    realistic_br: 10.3,
    simulator_br: 9.7,
    event: null,
    release_date: "2020-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 830000,
    req_exp: 300000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_7d.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_7d.png",
    },
  },
  {
    identifier: "a_7e",
    country: "usa",
    vehicle_type: "bomber",
    era: 7,
    arcade_br: 10.7,
    realistic_br: 10.7,
    simulator_br: 10,
    event: null,
    release_date: "2021-10-26 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 950000,
    req_exp: 175000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_7e.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_7e.png",
    },
  },
  {
    identifier: "a_7k",
    country: "usa",
    vehicle_type: "bomber",
    era: 7,
    arcade_br: 11,
    realistic_br: 11,
    simulator_br: 10,
    event: "craft_2023_spring",
    release_date: "2023-04-06 00:00:00",
    is_premium: false,
    is_gift: true,
    value: 950000,
    req_exp: 350000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/a_7k.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/a_7k.png",
    },
  },
  {
    identifier: "ab_205a_1",
    country: "italy",
    vehicle_type: "fighter",
    era: 5,
    arcade_br: 7.7,
    realistic_br: 7.7,
    simulator_br: 8,
    event: null,
    release_date: "2020-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 390000,
    req_exp: 0,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ab_205a_1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ab_205a_1.png",
    },
  },
  {
    identifier: "ah_1f",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 9.7,
    simulator_br: 9.7,
    event: null,
    release_date: "2018-09-11 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 990000,
    req_exp: 370000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1f.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1f.png",
    },
  },
  {
    identifier: "ah_1f_iaf",
    country: "israel",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 9.7,
    simulator_br: 9.7,
    event: null,
    release_date: "2022-06-15 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1000000,
    req_exp: 380000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1f_iaf.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1f_iaf.png",
    },
  },
  {
    identifier: "ah_1g",
    country: "usa",
    vehicle_type: "fighter",
    era: 5,
    arcade_br: 8.7,
    realistic_br: 8,
    simulator_br: 8,
    event: null,
    release_date: "2018-09-11 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 370000,
    req_exp: 0,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1g.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1g.png",
    },
  },
  {
    identifier: "ah_1g_iaf",
    country: "israel",
    vehicle_type: "fighter",
    era: 5,
    arcade_br: 8.7,
    realistic_br: 8,
    simulator_br: 8,
    event: null,
    release_date: "2022-06-15 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 390000,
    req_exp: 0,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1g_iaf.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1g_iaf.png",
    },
  },
  {
    identifier: "ah_1q_iaf",
    country: "israel",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9,
    realistic_br: 9,
    simulator_br: 9,
    event: null,
    release_date: "2022-06-15 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 980000,
    req_exp: 360000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1q_iaf.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1q_iaf.png",
    },
  },
  {
    identifier: "ah_1s",
    country: "japan",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 9.7,
    simulator_br: 9.7,
    event: null,
    release_date: "2019-05-28 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 380000,
    ge_cost: 7130,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1s.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1s.png",
    },
  },
  {
    identifier: "ah_1s_early",
    country: "japan",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 9.3,
    simulator_br: 9.3,
    event: null,
    release_date: "2020-06-01 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 980000,
    req_exp: 360000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1s_early.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1s_early.png",
    },
  },
  {
    identifier: "ah_1s_late",
    country: "japan",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 9.7,
    simulator_br: 9.7,
    event: null,
    release_date: "2020-06-01 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1000000,
    req_exp: 380000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1s_late.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1s_late.png",
    },
  },
  {
    identifier: "ah_1w",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10,
    realistic_br: 10.7,
    simulator_br: 10.7,
    event: null,
    release_date: "2024-03-13 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1000000,
    req_exp: 380000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1w.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1w.png",
    },
  },
  {
    identifier: "ah_1w_china",
    country: "china",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10,
    realistic_br: 10.7,
    simulator_br: 10.7,
    event: null,
    release_date: "2024-03-13 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1010000,
    req_exp: 390000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1w_china.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1w_china.png",
    },
  },
  {
    identifier: "ah_1z",
    country: "usa",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10.3,
    realistic_br: 11.3,
    simulator_br: 10,
    event: null,
    release_date: "2018-09-11 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1020000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_1z.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_1z.png",
    },
  },
  {
    identifier: "ah_2_rooivalk",
    country: "britain",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10.7,
    realistic_br: 11.3,
    simulator_br: 10.7,
    event: null,
    release_date: "2022-09-14 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 360000,
    ge_cost: 8560,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_2_rooivalk.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_2_rooivalk.png",
    },
  },
  {
    identifier: "ah_60_iaf",
    country: "israel",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10.7,
    realistic_br: 11.3,
    simulator_br: 10.7,
    event: null,
    release_date: "2024-03-13 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1020000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_60_iaf.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_60_iaf.png",
    },
  },
  {
    identifier: "ah_64a",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10.3,
    realistic_br: 11.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2020-03-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1010000,
    req_exp: 390000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_64a.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_64a.png",
    },
  },
  {
    identifier: "ah_64a_greece_usa",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10.3,
    realistic_br: 11.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2022-10-26 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 400000,
    ge_cost: 9270,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_64a_greece_usa.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_64a_greece_usa.png",
    },
  },
  {
    identifier: "ah_64a_iaf",
    country: "israel",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10.3,
    realistic_br: 11.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2022-06-15 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1010000,
    req_exp: 390000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_64a_iaf.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_64a_iaf.png",
    },
  },
  {
    identifier: "ah_64a_peten",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10.3,
    realistic_br: 11.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2020-03-10 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 400000,
    ge_cost: 9270,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_64a_peten.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_64a_peten.png",
    },
  },
  {
    identifier: "ah_64a_peten_iaf",
    country: "israel",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10.3,
    realistic_br: 11.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2022-03-22 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 400000,
    ge_cost: 9270,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_64a_peten_iaf.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_64a_peten_iaf.png",
    },
  },
  {
    identifier: "ah_64d",
    country: "usa",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10.7,
    realistic_br: 11.7,
    simulator_br: 10.7,
    event: null,
    release_date: "2020-03-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1020000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_64d.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_64d.png",
    },
  },
  {
    identifier: "ah_64d_i_saraph",
    country: "israel",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10.7,
    realistic_br: 11.3,
    simulator_br: 10.7,
    event: null,
    release_date: "2022-06-15 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1020000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_64d_i_saraph.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_64d_i_saraph.png",
    },
  },
  {
    identifier: "ah_64d_japan",
    country: "japan",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10.7,
    realistic_br: 11,
    simulator_br: 10.3,
    event: null,
    release_date: "2020-06-01 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1020000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_64d_japan.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_64d_japan.png",
    },
  },
  {
    identifier: "ah_6m",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 10.3,
    simulator_br: 10,
    event: null,
    release_date: "2023-03-07 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 990000,
    req_exp: 370000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_6m.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_6m.png",
    },
  },
  {
    identifier: "ah_mk1",
    country: "britain",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10.7,
    realistic_br: 11.7,
    simulator_br: 10.7,
    event: null,
    release_date: "2020-03-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1020000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ah_mk1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ah_mk1.png",
    },
  },
  {
    identifier: "ahs",
    country: "sweden",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10.3,
    realistic_br: 11.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2022-03-22 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1020000,
    req_exp: 400000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ahs.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ahs.png",
    },
  },
  {
    identifier: "aichi_e13a",
    country: "japan",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.3,
    simulator_br: 1.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 10000,
    req_exp: 7900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/aichi_e13a.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/aichi_e13a.png",
    },
  },
  {
    identifier: "alpha_jet_a",
    country: "germany",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9,
    realistic_br: 8.7,
    simulator_br: 9,
    event: null,
    release_date: "2024-03-13 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 450000,
    req_exp: 160000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/alpha_jet_a.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/alpha_jet_a.png",
    },
  },
  {
    identifier: "alpha_jet_e",
    country: "france",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9,
    realistic_br: 8.7,
    simulator_br: 9,
    event: null,
    release_date: "2024-03-13 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 520000,
    req_exp: 190000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/alpha_jet_e.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/alpha_jet_e.png",
    },
  },
  {
    identifier: "am_1_mauler",
    country: "usa",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.7,
    realistic_br: 5.7,
    simulator_br: 5.3,
    event: null,
    release_date: "2019-05-28 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 210000,
    req_exp: 35000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/am_1_mauler.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/am_1_mauler.png",
    },
  },
  {
    identifier: "amx",
    country: "italy",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10.3,
    realistic_br: 10.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2023-12-14 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 830000,
    req_exp: 300000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/amx.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/amx.png",
    },
  },
  {
    identifier: "ar_2",
    country: "ussr",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 2.7,
    realistic_br: 2.3,
    simulator_br: 2.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 6300,
    req_exp: 5900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ar_2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ar_2.png",
    },
  },
  {
    identifier: "arado-196a-3",
    country: "germany",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.7,
    realistic_br: 1.3,
    simulator_br: 1.7,
    event: "summer_2020",
    release_date: "2020-08-25 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 4000,
    ge_cost: 400,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/arado-196a-3.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/arado-196a-3.png",
    },
  },
  {
    identifier: "arado-196a-5",
    country: "sweden",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.7,
    realistic_br: 1.3,
    simulator_br: 1.7,
    event: null,
    release_date: "2022-09-14 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 4000,
    ge_cost: 400,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/arado-196a-5.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/arado-196a-5.png",
    },
  },
  {
    identifier: "arado-234",
    country: "germany",
    vehicle_type: "bomber",
    era: 5,
    arcade_br: 6.3,
    realistic_br: 6.3,
    simulator_br: 6.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 240000,
    req_exp: 82000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/arado-234.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/arado-234.png",
    },
  },
  {
    identifier: "arado-234c-3",
    country: "germany",
    vehicle_type: "bomber",
    era: 5,
    arcade_br: 8,
    realistic_br: 7.3,
    simulator_br: 7.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 270000,
    req_exp: 48000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/arado-234c-3.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/arado-234c-3.png",
    },
  },
  {
    identifier: "ariete",
    country: "italy",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.3,
    realistic_br: 9.3,
    simulator_br: 9,
    event: null,
    release_date: "2022-06-15 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 160000,
    ge_cost: 8730,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ariete.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ariete.png",
    },
  },
  {
    identifier: "attaker_fb1",
    country: "britain",
    vehicle_type: "fighter",
    era: 5,
    arcade_br: 7,
    realistic_br: 7,
    simulator_br: 7.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 270000,
    req_exp: 95000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/attaker_fb1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/attaker_fb1.png",
    },
  },
  {
    identifier: "attaker_fb2",
    country: "britain",
    vehicle_type: "fighter",
    era: 5,
    arcade_br: 7,
    realistic_br: 7,
    simulator_br: 7.3,
    event: null,
    release_date: "2021-03-10 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 95000,
    ge_cost: 8020,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/attaker_fb2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/attaker_fb2.png",
    },
  },
  {
    identifier: "av_8a",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.3,
    realistic_br: 9.7,
    simulator_br: 9.7,
    event: null,
    release_date: "2020-11-15 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 190000,
    ge_cost: 8910,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/av_8a.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/av_8a.png",
    },
  },
  {
    identifier: "av_8b_plus_italy",
    country: "italy",
    vehicle_type: "fighter",
    era: 8,
    arcade_br: 12.3,
    realistic_br: 11.7,
    simulator_br: 11.7,
    event: null,
    release_date: "2023-09-19 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 1100000,
    req_exp: 410000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/av_8b_plus_italy.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/av_8b_plus_italy.png",
    },
  },
  {
    identifier: "av_8c",
    country: "usa",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 9.7,
    simulator_br: 9.7,
    event: null,
    release_date: "2020-11-15 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 620000,
    req_exp: 220000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/av_8c.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/av_8c.png",
    },
  },
  {
    identifier: "avenger_mk1",
    country: "britain",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 1.7,
    realistic_br: 1.7,
    simulator_br: 2,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 11000,
    ge_cost: 1000,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/avenger_mk1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/avenger_mk1.png",
    },
  },
  {
    identifier: "b-17e",
    country: "usa",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 4.7,
    realistic_br: 4.7,
    simulator_br: 5.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 76000,
    req_exp: 26000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b-17e.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b-17e.png",
    },
  },
  {
    identifier: "b-17e_japan",
    country: "japan",
    vehicle_type: "bomber",
    era: 4,
    arcade_br: 4.7,
    realistic_br: 4.7,
    simulator_br: 5.7,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 54000,
    ge_cost: 4900,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b-17e_japan.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b-17e_japan.png",
    },
  },
  {
    identifier: "b-17e_late",
    country: "usa",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 4.7,
    realistic_br: 5,
    simulator_br: 5.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 105000,
    req_exp: 17000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b-17e_late.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b-17e_late.png",
    },
  },
  {
    identifier: "b-17g",
    country: "usa",
    vehicle_type: "bomber",
    era: 4,
    arcade_br: 5,
    realistic_br: 5.3,
    simulator_br: 6.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 155000,
    req_exp: 46000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b-17g.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b-17g.png",
    },
  },
  {
    identifier: "b-17g_iaf",
    country: "israel",
    vehicle_type: "bomber",
    era: 4,
    arcade_br: 5,
    realistic_br: 5.3,
    simulator_br: 6.3,
    event: null,
    release_date: "2021-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 200000,
    req_exp: 63000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b-17g_iaf.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b-17g_iaf.png",
    },
  },
  {
    identifier: "b-29",
    country: "usa",
    vehicle_type: "bomber",
    era: 4,
    arcade_br: 7,
    realistic_br: 7.3,
    simulator_br: 7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 200000,
    req_exp: 63000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b-29.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b-29.png",
    },
  },
  {
    identifier: "b-57",
    country: "usa",
    vehicle_type: "bomber",
    era: 5,
    arcade_br: 8,
    realistic_br: 8.3,
    simulator_br: 7.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 300000,
    req_exp: 105000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b-57.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b-57.png",
    },
  },
  {
    identifier: "b-57b",
    country: "usa",
    vehicle_type: "bomber",
    era: 5,
    arcade_br: 8.3,
    realistic_br: 8.3,
    simulator_br: 8,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 340000,
    req_exp: 61000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b-57b.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b-57b.png",
    },
  },
  {
    identifier: "b5n2",
    country: "japan",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 1,
    realistic_br: 1.3,
    simulator_br: 1.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 700,
    req_exp: 2900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b5n2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b5n2.png",
    },
  },
  {
    identifier: "b6n1",
    country: "japan",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 1.7,
    realistic_br: 1.7,
    simulator_br: 2,
    event: null,
    release_date: "2020-06-01 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 6300,
    req_exp: 5900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b6n1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b6n1.png",
    },
  },
  {
    identifier: "b6n2",
    country: "japan",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 2,
    realistic_br: 2.3,
    simulator_br: 2.3,
    event: null,
    release_date: "2020-06-01 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 10000,
    req_exp: 7900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b6n2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b6n2.png",
    },
  },
  {
    identifier: "b6n2a",
    country: "japan",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 2,
    realistic_br: 2.3,
    simulator_br: 2.3,
    event: null,
    release_date: "2020-06-01 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 16000,
    req_exp: 4600,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b6n2a.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b6n2a.png",
    },
  },
  {
    identifier: "b7a2",
    country: "japan",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 4,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 76000,
    req_exp: 26000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b7a2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b7a2.png",
    },
  },
  {
    identifier: "b7a2_homare_23",
    country: "japan",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 4,
    event: "battlepass_season12",
    release_date: "2023-07-26 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 33000,
    ge_cost: 1600,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b7a2_homare_23.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b7a2_homare_23.png",
    },
  },
  {
    identifier: "b_10b",
    country: "usa",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.3,
    simulator_br: 1.7,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 4000,
    ge_cost: 400,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_10b.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_10b.png",
    },
  },
  {
    identifier: "b_18a",
    country: "usa",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.3,
    simulator_br: 1.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 2100,
    req_exp: 2000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_18a.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_18a.png",
    },
  },
  {
    identifier: "b_239_finland",
    country: "sweden",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 2.7,
    realistic_br: 2.7,
    simulator_br: 2.3,
    event: null,
    release_date: "2022-10-26 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 10000,
    req_exp: 7900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_239_finland.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_239_finland.png",
    },
  },
  {
    identifier: "b_24d",
    country: "usa",
    vehicle_type: "bomber",
    era: 4,
    arcade_br: 5,
    realistic_br: 5.7,
    simulator_br: 6,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 185000,
    req_exp: 27000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_24d.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_24d.png",
    },
  },
  {
    identifier: "b_25j_1",
    country: "usa",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 3.7,
    realistic_br: 4,
    simulator_br: 3.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 16000,
    req_exp: 9200,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_25j_1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_25j_1.png",
    },
  },
  {
    identifier: "b_25j_20",
    country: "usa",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 4,
    realistic_br: 4,
    simulator_br: 4.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 22000,
    req_exp: 11000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_25j_20.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_25j_20.png",
    },
  },
  {
    identifier: "b_25j_30_china",
    country: "china",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 4,
    realistic_br: 4,
    simulator_br: 4.3,
    event: null,
    release_date: "2019-09-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 47000,
    req_exp: 18000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_25j_30_china.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_25j_30_china.png",
    },
  },
  {
    identifier: "b_25j_30_vvs_ussr",
    country: "ussr",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 4,
    realistic_br: 4,
    simulator_br: 4.3,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 26000,
    ge_cost: 1450,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_25j_30_vvs_ussr.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_25j_30_vvs_ussr.png",
    },
  },
  {
    identifier: "b_26b_c",
    country: "usa",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 4.3,
    realistic_br: 4.3,
    simulator_br: 4.7,
    event: null,
    release_date: "2022-03-22 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 47000,
    req_exp: 18000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_26b_c.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_26b_c.png",
    },
  },
  {
    identifier: "b_26c_france",
    country: "france",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 4.3,
    realistic_br: 4.7,
    simulator_br: 4.7,
    event: null,
    release_date: "2022-03-22 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 47000,
    req_exp: 18000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_26c_france.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_26c_france.png",
    },
  },
  {
    identifier: "b_34",
    country: "usa",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 2.7,
    realistic_br: 3.3,
    simulator_br: 2.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 10000,
    req_exp: 7900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_34.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_34.png",
    },
  },
  {
    identifier: "b_48_firecrest",
    country: "britain",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 2.7,
    realistic_br: 2.3,
    simulator_br: 3.3,
    event: null,
    release_date: "2019-03-26 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 32000,
    req_exp: 155000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/b_48_firecrest.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/b_48_firecrest.png",
    },
  },
  {
    identifier: "ba_65_k14_l",
    country: "italy",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.7,
    realistic_br: 1.3,
    simulator_br: 1.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 700,
    req_exp: 2900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/ba_65_k14_l.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/ba_65_k14_l.png",
    },
  },
  {
    identifier: "bb-1",
    country: "ussr",
    vehicle_type: "stormovik",
    era: 1,
    arcade_br: 1.7,
    realistic_br: 1.3,
    simulator_br: 1.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 700,
    req_exp: 2900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bb-1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bb-1.png",
    },
  },
  {
    identifier: "be_6",
    country: "ussr",
    vehicle_type: "bomber",
    era: 4,
    arcade_br: 5,
    realistic_br: 5,
    simulator_br: 5.3,
    event: null,
    release_date: "2018-10-23 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 54000,
    ge_cost: 3850,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/be_6.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/be_6.png",
    },
  },
  {
    identifier: "beaufighter_mk1_40mm",
    country: "britain",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 2,
    realistic_br: 2.3,
    simulator_br: 3.3,
    event: "battlepass_season5",
    release_date: "2021-10-26 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 9200,
    ge_cost: 850,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/beaufighter_mk1_40mm.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/beaufighter_mk1_40mm.png",
    },
  },
  {
    identifier: "beaufighter_mk21",
    country: "britain",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 3.7,
    simulator_br: 4,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 32000,
    req_exp: 6900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/beaufighter_mk21.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/beaufighter_mk21.png",
    },
  },
  {
    identifier: "beaufighter_mk6c",
    country: "britain",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 2.3,
    realistic_br: 3,
    simulator_br: 3.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 16000,
    req_exp: 9200,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/beaufighter_mk6c.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/beaufighter_mk6c.png",
    },
  },
  {
    identifier: "beaufighter_mkx",
    country: "britain",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 2.7,
    realistic_br: 3,
    simulator_br: 3.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 22000,
    req_exp: 5600,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/beaufighter_mkx.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/beaufighter_mkx.png",
    },
  },
  {
    identifier: "beaufort_mkviii",
    country: "britain",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.7,
    simulator_br: 2,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 6300,
    req_exp: 3000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/beaufort_mkviii.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/beaufort_mkviii.png",
    },
  },
  {
    identifier: "bf-109a_1",
    country: "germany",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.3,
    simulator_br: 1.3,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 2900,
    ge_cost: 250,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109a_1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109a_1.png",
    },
  },
  {
    identifier: "bf-109b_2",
    country: "germany",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.7,
    realistic_br: 1.3,
    simulator_br: 1.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 700,
    req_exp: 2900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109b_2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109b_2.png",
    },
  },
  {
    identifier: "bf-109c_1",
    country: "germany",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 2,
    realistic_br: 1.7,
    simulator_br: 1.7,
    event: null,
    release_date: "2024-03-13 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 2100,
    req_exp: 4000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109c_1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109c_1.png",
    },
  },
  {
    identifier: "bf-109e-1",
    country: "germany",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 2.3,
    realistic_br: 2.3,
    simulator_br: 2,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 10000,
    req_exp: 7900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109e-1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109e-1.png",
    },
  },
  {
    identifier: "bf-109e-3",
    country: "germany",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 2.7,
    realistic_br: 2.3,
    simulator_br: 2.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 16000,
    req_exp: 9200,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109e-3.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109e-3.png",
    },
  },
  {
    identifier: "bf-109e-3_japan",
    country: "japan",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 3,
    simulator_br: 2.7,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 11000,
    ge_cost: 1000,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109e-3_japan.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109e-3_japan.png",
    },
  },
  {
    identifier: "bf-109e-4",
    country: "germany",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 3,
    simulator_br: 3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 22000,
    req_exp: 5600,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109e-4.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109e-4.png",
    },
  },
  {
    identifier: "bf-109e-7",
    country: "germany",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 3,
    simulator_br: 3,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 9200,
    ge_cost: 850,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109e-7.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109e-7.png",
    },
  },
  {
    identifier: "bf-109f-1",
    country: "germany",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 2.7,
    simulator_br: 3.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 22000,
    req_exp: 11000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109f-1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109f-1.png",
    },
  },
  {
    identifier: "bf-109f-2",
    country: "germany",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 3,
    simulator_br: 3.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 32000,
    req_exp: 6900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109f-2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109f-2.png",
    },
  },
  {
    identifier: "bf-109f-4",
    country: "germany",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4.3,
    realistic_br: 4,
    simulator_br: 4,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 47000,
    req_exp: 18000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109f-4.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109f-4.png",
    },
  },
  {
    identifier: "bf-109f-4_hungary",
    country: "italy",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4.3,
    realistic_br: 4,
    simulator_br: 4,
    event: "battlepass_season10",
    release_date: "2023-01-25 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 33000,
    ge_cost: 1600,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109f-4_hungary.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109f-4_hungary.png",
    },
  },
  {
    identifier: "bf-109f-4_trop",
    country: "germany",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4.3,
    realistic_br: 4,
    simulator_br: 4,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 76000,
    req_exp: 13000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109f-4_trop.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109f-4_trop.png",
    },
  },
  {
    identifier: "bf-109f-4_usa",
    country: "usa",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4.3,
    realistic_br: 4,
    simulator_br: 4,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 26000,
    ge_cost: 1450,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109f-4_usa.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109f-4_usa.png",
    },
  },
  {
    identifier: "bf-109g-10",
    country: "germany",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.7,
    realistic_br: 5.7,
    simulator_br: 5.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 200000,
    req_exp: 31000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-10.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-10.png",
    },
  },
  {
    identifier: "bf-109g-14",
    country: "germany",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.7,
    realistic_br: 5.3,
    simulator_br: 5,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 185000,
    req_exp: 54000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-14.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-14.png",
    },
  },
  {
    identifier: "bf-109g-14as",
    country: "italy",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.7,
    realistic_br: 5.3,
    simulator_br: 5,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 185000,
    req_exp: 54000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-14as.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-14as.png",
    },
  },
  {
    identifier: "bf-109g-2",
    country: "germany",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.3,
    realistic_br: 4.3,
    simulator_br: 4.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 155000,
    req_exp: 46000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-2.png",
    },
  },
  {
    identifier: "bf-109g-2_finland",
    country: "sweden",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.3,
    realistic_br: 4.3,
    simulator_br: 4.3,
    event: null,
    release_date: "2022-10-26 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 155000,
    req_exp: 46000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-2_finland.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-2_finland.png",
    },
  },
  {
    identifier: "bf-109g-2_hungary",
    country: "italy",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.3,
    realistic_br: 4.3,
    simulator_br: 4.3,
    event: null,
    release_date: "2019-08-20 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 54000,
    ge_cost: 4640,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-2_hungary.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-2_hungary.png",
    },
  },
  {
    identifier: "bf-109g-2_romania",
    country: "germany",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 5.3,
    realistic_br: 4.3,
    simulator_br: 4.3,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 26000,
    ge_cost: 1450,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-2_romania.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-2_romania.png",
    },
  },
  {
    identifier: "bf-109g-6",
    country: "germany",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.3,
    realistic_br: 4.7,
    simulator_br: 4.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 185000,
    req_exp: 27000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-6.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-6.png",
    },
  },
  {
    identifier: "bf-109g-6_erla_finland",
    country: "sweden",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.3,
    realistic_br: 4.7,
    simulator_br: 4.7,
    event: null,
    release_date: "2022-10-26 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 185000,
    req_exp: 27000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-6_erla_finland.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-6_erla_finland.png",
    },
  },
  {
    identifier: "bf-109g-6_finland",
    country: "sweden",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 5.3,
    realistic_br: 4.7,
    simulator_br: 4.7,
    event: null,
    release_date: "2021-06-02 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 63000,
    ge_cost: 4880,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109g-6_finland.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109g-6_finland.png",
    },
  },
  {
    identifier: "bf-109k-4",
    country: "germany",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 6.3,
    realistic_br: 5.7,
    simulator_br: 5.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 210000,
    req_exp: 71000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109k-4.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109k-4.png",
    },
  },
  {
    identifier: "bf-109z",
    country: "germany",
    vehicle_type: "fighter",
    era: 4,
    arcade_br: 4.7,
    realistic_br: 4.7,
    simulator_br: 4.7,
    event: null,
    release_date: "2018-06-06 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 46000,
    ge_cost: 2980,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-109z.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-109z.png",
    },
  },
  {
    identifier: "bf-110c-4",
    country: "germany",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 2.7,
    simulator_br: 3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 22000,
    req_exp: 11000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-110c-4.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-110c-4.png",
    },
  },
  {
    identifier: "bf-110c-6",
    country: "germany",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 3,
    simulator_br: 3,
    event: "summer_2019",
    release_date: null,
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 11000,
    ge_cost: 1000,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-110c-6.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-110c-6.png",
    },
  },
  {
    identifier: "bf-110f-2",
    country: "germany",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3,
    realistic_br: 3,
    simulator_br: 3.3,
    event: null,
    release_date: "2018-06-06 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 32000,
    req_exp: 6900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-110f-2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-110f-2.png",
    },
  },
  {
    identifier: "bf-110g-2",
    country: "germany",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 3.7,
    event: null,
    release_date: "2018-06-06 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 47000,
    req_exp: 18000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf-110g-2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf-110g-2.png",
    },
  },
  {
    identifier: "bf2c_1",
    country: "usa",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1,
    realistic_br: 1,
    simulator_br: 1,
    event: null,
    release_date: "2023-06-14 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 0,
    req_exp: 0,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf2c_1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf2c_1.png",
    },
  },
  {
    identifier: "bf_110g_4",
    country: "germany",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 3.7,
    event: null,
    release_date: "2020-11-15 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 76000,
    req_exp: 13000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf_110g_4.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf_110g_4.png",
    },
  },
  {
    identifier: "bf_110g_4_hungary",
    country: "italy",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 3.7,
    event: null,
    release_date: "2020-09-08 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 26000,
    ge_cost: 1450,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bf_110g_4_hungary.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bf_110g_4_hungary.png",
    },
  },
  {
    identifier: "bi",
    country: "ussr",
    vehicle_type: "fighter",
    era: 5,
    arcade_br: 6.7,
    realistic_br: 6.7,
    simulator_br: 6.3,
    event: "craft_2020_autumn",
    release_date: "2020-09-30 00:00:00",
    is_premium: false,
    is_gift: true,
    value: 270000,
    req_exp: 95000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bi.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bi.png",
    },
  },
  {
    identifier: "blenheim_mkiv",
    country: "britain",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.3,
    simulator_br: 1.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 2100,
    req_exp: 4000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/blenheim_mkiv.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/blenheim_mkiv.png",
    },
  },
  {
    identifier: "bo_105cb2",
    country: "germany",
    vehicle_type: "fighter",
    era: 5,
    arcade_br: 9.7,
    realistic_br: 9.3,
    simulator_br: 9.7,
    event: null,
    release_date: "2018-10-23 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 360000,
    ge_cost: 8560,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bo_105cb2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bo_105cb2.png",
    },
  },
  {
    identifier: "bo_105pah1",
    country: "germany",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 9.3,
    simulator_br: 9.7,
    event: null,
    release_date: "2018-10-23 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 980000,
    req_exp: 360000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bo_105pah1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bo_105pah1.png",
    },
  },
  {
    identifier: "bo_105pah1_a1",
    country: "germany",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 9.3,
    simulator_br: 9.7,
    event: null,
    release_date: "2018-10-23 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 990000,
    req_exp: 370000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bo_105pah1_a1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bo_105pah1_a1.png",
    },
  },
  {
    identifier: "boomerang_mki",
    country: "britain",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3.3,
    realistic_br: 3,
    simulator_br: 2.7,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 14000,
    ge_cost: 1150,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/boomerang_mki.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/boomerang_mki.png",
    },
  },
  {
    identifier: "boomerang_mkii",
    country: "britain",
    vehicle_type: "fighter",
    era: 2,
    arcade_br: 3.3,
    realistic_br: 3,
    simulator_br: 2.7,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 14000,
    ge_cost: 1320,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/boomerang_mkii.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/boomerang_mkii.png",
    },
  },
  {
    identifier: "boston_mk_1",
    country: "britain",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 2.3,
    realistic_br: 2.3,
    simulator_br: 2.3,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 7900,
    ge_cost: 700,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/boston_mk_1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/boston_mk_1.png",
    },
  },
  {
    identifier: "br_20_dr",
    country: "italy",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 1.7,
    realistic_br: 1.7,
    simulator_br: 1.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 2100,
    req_exp: 4000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/br_20_dr.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/br_20_dr.png",
    },
  },
  {
    identifier: "br_20m_m1",
    country: "italy",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 1.7,
    realistic_br: 1.7,
    simulator_br: 1.7,
    event: null,
    release_date: "2019-10-29 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 6300,
    req_exp: 3000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/br_20m_m1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/br_20m_m1.png",
    },
  },
  {
    identifier: "br_693_ab2",
    country: "france",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 2,
    realistic_br: 1.7,
    simulator_br: 1.7,
    event: null,
    release_date: "2019-10-29 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 2100,
    req_exp: 4000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/br_693_ab2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/br_693_ab2.png",
    },
  },
  {
    identifier: "breda_88",
    country: "italy",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.7,
    realistic_br: 1.7,
    simulator_br: 2,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 2100,
    req_exp: 4000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/breda_88.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/breda_88.png",
    },
  },
  {
    identifier: "brigand_b1",
    country: "britain",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 4,
    simulator_br: 4.3,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 105000,
    req_exp: 33000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/brigand_b1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/brigand_b1.png",
    },
  },
  {
    identifier: "btd-1",
    country: "usa",
    vehicle_type: "bomber",
    era: 3,
    arcade_br: 3.7,
    realistic_br: 4,
    simulator_br: 4,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 40000,
    ge_cost: 1750,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/btd-1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/btd-1.png",
    },
  },
  {
    identifier: "buccaneer_s1",
    country: "britain",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 9.7,
    realistic_br: 8.7,
    simulator_br: 9,
    event: "summer_2021",
    release_date: "2021-08-06 00:00:00",
    is_premium: false,
    is_gift: true,
    value: 450000,
    req_exp: 160000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/buccaneer_s1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/buccaneer_s1.png",
    },
  },
  {
    identifier: "buccaneer_s2",
    country: "britain",
    vehicle_type: "fighter",
    era: 6,
    arcade_br: 10.3,
    realistic_br: 9.3,
    simulator_br: 9.3,
    event: null,
    release_date: "2020-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 520000,
    req_exp: 190000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/buccaneer_s2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/buccaneer_s2.png",
    },
  },
  {
    identifier: "buccaneer_s2b",
    country: "britain",
    vehicle_type: "fighter",
    era: 7,
    arcade_br: 10,
    realistic_br: 10.3,
    simulator_br: 10.3,
    event: null,
    release_date: "2024-03-13 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 830000,
    req_exp: 300000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/buccaneer_s2b.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/buccaneer_s2b.png",
    },
  },
  {
    identifier: "bv-138c-1",
    country: "germany",
    vehicle_type: "bomber",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.7,
    simulator_br: 1.7,
    event: null,
    release_date: "2021-09-07 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 2100,
    req_exp: 2000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bv-138c-1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bv-138c-1.png",
    },
  },
  {
    identifier: "bv-155b-1",
    country: "germany",
    vehicle_type: "fighter",
    era: 3,
    arcade_br: 4,
    realistic_br: 3.7,
    simulator_br: 4,
    event: "battlepass_season8",
    release_date: "2022-07-27 00:00:00",
    is_premium: true,
    is_gift: true,
    value: 0,
    req_exp: 26000,
    ge_cost: 1450,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bv-155b-1.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bv-155b-1.png",
    },
  },
  {
    identifier: "bv-238",
    country: "germany",
    vehicle_type: "bomber",
    era: 2,
    arcade_br: 3.7,
    realistic_br: 3.7,
    simulator_br: 4,
    event: null,
    release_date: null,
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 18000,
    ge_cost: 1840,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/bv-238.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/bv-238.png",
    },
  },
  {
    identifier: "canberra_bimk6",
    country: "britain",
    vehicle_type: "bomber",
    era: 5,
    arcade_br: 9,
    realistic_br: 8.3,
    simulator_br: 8,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 340000,
    req_exp: 61000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/canberra_bimk6.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/canberra_bimk6.png",
    },
  },
  {
    identifier: "canberra_bmk2",
    country: "britain",
    vehicle_type: "bomber",
    era: 5,
    arcade_br: 8.7,
    realistic_br: 8.3,
    simulator_br: 7.7,
    event: null,
    release_date: null,
    is_premium: false,
    is_gift: false,
    value: 300000,
    req_exp: 105000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/canberra_bmk2.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/canberra_bmk2.png",
    },
  },
  {
    identifier: "caudron_cr714",
    country: "france",
    vehicle_type: "fighter",
    era: 1,
    arcade_br: 1.3,
    realistic_br: 1.3,
    simulator_br: 1.3,
    event: null,
    release_date: "2017-10-27 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 700,
    req_exp: 2900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/caudron_cr714.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/caudron_cr714.png",
    },
  },
  {
    identifier: "cn_bt_5",
    country: "china",
    vehicle_type: "lighttank",
    era: 1,
    arcade_br: 1,
    realistic_br: 1,
    simulator_br: 1,
    event: null,
    release_date: "2019-09-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 700,
    req_exp: 2900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/cn_bt_5.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/cn_bt_5.png",
    },
  },
  {
    identifier: "cn_cm11",
    country: "china",
    vehicle_type: "mediumtank",
    era: 6,
    arcade_br: 9.3,
    realistic_br: 9.3,
    simulator_br: 9.3,
    event: null,
    release_date: "2019-09-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 620000,
    req_exp: 220000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/cn_cm11.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/cn_cm11.png",
    },
  },
  {
    identifier: "cn_cm_25",
    country: "china",
    vehicle_type: "tankdestroyer",
    era: 6,
    arcade_br: 8.7,
    realistic_br: 8.7,
    simulator_br: 8.7,
    event: null,
    release_date: "2020-09-08 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 450000,
    req_exp: 160000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/cn_cm_25.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/cn_cm_25.png",
    },
  },
  {
    identifier: "cn_gmc_cckw_353_m45_quad",
    country: "china",
    vehicle_type: "spaa",
    era: 2,
    arcade_br: 2.3,
    realistic_br: 2.3,
    simulator_br: 2.3,
    event: null,
    release_date: "2020-12-17 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 10000,
    req_exp: 7900,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/cn_gmc_cckw_353_m45_quad.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/cn_gmc_cckw_353_m45_quad.png",
    },
  },
  {
    identifier: "cn_hj_9",
    country: "china",
    vehicle_type: "tankdestroyer",
    era: 6,
    arcade_br: 9,
    realistic_br: 9,
    simulator_br: 9,
    event: null,
    release_date: "2022-09-14 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 620000,
    req_exp: 110000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/cn_hj_9.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/cn_hj_9.png",
    },
  },
  {
    identifier: "cn_is_2_1943",
    country: "china",
    vehicle_type: "heavytank",
    era: 4,
    arcade_br: 6.3,
    realistic_br: 6.3,
    simulator_br: 6.3,
    event: null,
    release_date: "2019-09-10 00:00:00",
    is_premium: false,
    is_gift: false,
    value: 200000,
    req_exp: 63000,
    ge_cost: 0,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/cn_is_2_1943.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/cn_is_2_1943.png",
    },
  },
  {
    identifier: "cn_is_2_1943_no402",
    country: "china",
    vehicle_type: "heavytank",
    era: 4,
    arcade_br: 6.3,
    realistic_br: 6.3,
    simulator_br: 6.3,
    event: null,
    release_date: "2020-01-20 00:00:00",
    is_premium: true,
    is_gift: false,
    value: 0,
    req_exp: 71000,
    ge_cost: 6090,
    images: {
      image: "wtvehiclesapi.sgambe.serv00.net/assets/images/cn_is_2_1943_no402.png",
      techtree: "wtvehiclesapi.sgambe.serv00.net/assets/techtrees/cn_is_2_1943_no402.png",
    },
  },
]
